### ISSUE TITLE
Rounding error in binning function

### ISSUE THREAD

**Issue by pietroquaglio** [NeuralEnsemble/elephant#196] opened 2018-12-26 14:00 UTC
The BinnedSpikeTrain class introduce an error in the binned spike train with specific binsizes. I suspect it is due to a rounding error when the bin index is computed by dividing the spike times with the binsize (line 797 of conversion.py). Here a minimal example to reproduce the error:
```
binsize = 1/(30000. * pq.Hz)
st_1 = neo.SpikeTrain([61529]*binsize, t_stop=61530*binsize, t_start=61528*binsize)
st_2 = neo.SpikeTrain([61528]*binsize, t_stop=61530*binsize, t_start=61528*binsize)
binned_sts = conv.BinnedSpikeTrain([st_1,st_2], binsize=binsize).to_sparse_array()
print(binned_sts)
```
The spikes fall both in the same bin (the first):
```
(0,0)       1
(1,0)       1
```
, while they should be in two successive bins:
```
(0,1)       1
(1,0)       1
```

(Running neo 0.7.0.dev and quantities 0.12.11)

**Comment by Kleinjohann** [comment] 2019-01-08 09:07
I have also experienced this issue. It arises most prominently when the binsize is a multiple of the sampling rate and when the possible spike times are t_start + n * sampling_rate for integers n (which is of course very common). Since t_start becomes the left edge of the first bin, all bin edges exactly coincide with possible spike times and it is basically up to chance in which bins these spikes are counted. 

This can be fixed by shifting the bins by sampling_rate/2 if the rate is known, then the spike times never end up on bin edges.

**Comment by mdenker** [comment] 2019-01-17 11:58
Worked on at https://github.com/INM-6/elephant/tree/fix/196

**Comment by Kleinjohann** [comment] 2019-01-17 15:02
I fixed the other tests that failed.

However, I realised that while our modifications make sense and prevent errors which might occur in some rare cases, they cannot fix the problem in Pietro's example. This is due to the fact that his example basically simulates spike trains with a fixed sampling rate. As we discussed our modifications do not help in that case. 

See above for Pietro's code. When constructing the spike trains we already make rounding errors in the calculations 
`binsize = 1/(30000. * pq.Hz), times = [61529] * binsize,
t_stop = 61530 * binsize, t_start = 61528 * binsize`
In the binning function we then compare the results of these calculations to the bin edges which are calculated as
`[t_start + i * binsize for i in range(num_bins)]`
This does not necessarily yield the same result as 
`[61528*binsize, 61529*binsize, 61530*binsize]`
so our checks do not work.

Even the number of bins is wrong as we've seen already. The calculation yields 
`num_bins before parsing to int:  1.9999999999997797`
so our additional check 
`t_stop - t_start - num_bins * binsize < binsize`
yields something like
`3.333333333332599e-05 1/Hz < 3.3333333333333335e-05 1/Hz`
and is ineffective as well.

If the input spike trains are already plagued with rounding errors then the only way I see to fix this in the binning (if we want to fix it) is shifting the bins to allow for some spread.

**Comment by AlexVanMeegen** [comment] 2019-11-12 21:34
Just stumbled across this and it looks strangely familiar. I suspect @pietroquaglio is right in his first comment when attributing it to the division by the binsize.

To me, it looks like the problem is something like this: `int(6.6e0/3.3e-2)` yields `199` instead of `200` due to numerical inaccuracies in float division, i.e. `int(6.6e0/3.3e-2) = int(199.99999999999997) = 199`. In conversion.py the time is divided by the binsize and cast to int to determine the number of the bin. If the same floating point inaccuracy as in the simple example occurs, the spike ends up one bin shifted to the left - as in Pie's example.

My best-working fix for this so far is to round before casting to int, see https://github.com/NeuralEnsemble/elephant/blob/master/elephant/spike_train_correlation.py#L803
Of course this requires the time to be an integer multiple of the binsize, thus it might not yet be the full solution. I'd be interested to discuss if you have a smart solution!

**Comment by Kleinjohann** [comment] 2019-11-27 13:29
Thanks for reviving this discussion @AlexVanMeegen 

Yes, some clever rounding might work. 
As you implied we only need to round 'upwards' since casting to integer takes the floor. We need some check to ensure compatibility with spike times that are not mutiples of the binsize.
Maybe something like
```
if next_bin_edge - current_value < parameter_to_be_determined * machine_precision:
    current_value = ceil(current_value)
```
right before casting to integer.

See also https://github.com/numpy/numpy/blob/d9b1e32cb8ef90d6b4a47853241db2a28146a57d/numpy/lib/histograms.py#L847-L854
The exact method used in numpy does not work in our case since the original spike times can already be plagued with rounding issues, but we may be able to apply the same idea.

**Comment by dizcza** [comment] 2020-04-01 13:36
Reopen if you still encounter the issue after Alex's fix.

**Closed by dizcza** 2020-04-01 13:36 UTC
Labels: bug
