### ISSUE TITLE
Elephant GPFA not running

### ISSUE THREAD

**Issue by Sary789** [NeuralEnsemble/elephant#442] opened 2021-12-24 20:36 UTC
**Questions and Help**

Hello, I am trying to run the tutorial on GPFA on my jupyter notebook, but it seems I cannot import GPFA because when I type "from elephant.gpfa import GPFA" I keep receiving the following error: "cannot import name 'float_factorial' from 'scipy._lib._util' (../opt/anaconda3/lib/python3.7/site-packages/scipy/_lib/_util.py). Does anyone know how I can solve this? Any suggestions will be greatly appreciated!

**Comment by Moritz-Alexander-Kern** [comment] 2022-01-03 09:20
Hello Sary789,
thank you for reporting this.

Looking at the error message, this seems to be related to scipy.
Unfortunately I wasn't able to reproduce this behavior with the following setup:

**Environment**

-  OS: Linux
-   Python version: 3.8.10
-   neo  version: 0.10.0
-   elephant  version: 0.10.0
-  scipy version: 1.6.3

**Expected behavior**
The following error: 
_"cannot import name 'float_factorial' from 'scipy._lib._util' (../opt/anaconda3/lib/python3.7/site-packages/scipy/_lib/_util.py)_


Further information on the environment you are running could be helpful:
Which version of elephant and scipy are you using? (elephant requires scipy<1.7.0)

**Comment by Moritz-Alexander-Kern** [comment] 2022-04-14 13:10
We are closing this now, but feel free to contact if the problem persists.

**Closed by Moritz-Alexander-Kern** 2022-04-14 13:10 UTC
