### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib;

### ISSUE THREAD

**Issue by lbazan** [NeuralEnsemble/elephant#224] opened 2019-06-07 20:48 UTC
BUILDSTDERR: /usr/lib64/python3.7/site-packages/sklearn/externals/six.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
BUILDSTDERR:   import imp
BUILDSTDERR: /usr/lib64/python3.7/site-packages/sklearn/utils/__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
BUILDSTDERR:   from collections import Sequence
BUILDSTDERR: /usr/lib/python3.7/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Example in the docstring of <function joint_probability_matrix at 0x7f74d45da598> in ../elephant/asset.py.
BUILDSTDERR:   warn(msg)
BUILDSTDERR: Exception occurred:
BUILDSTDERR:   File "/usr/lib/python3.7/site-packages/numpydoc/docscrape.py", line 330, in _parse_see_also
BUILDSTDERR:     raise ParseError("%s is not a item name" % line)
BUILDSTDERR: numpydoc.docscrape.ParseError: probability_matrix_analytical() for analytical derivation of the matrix is not a item name in "Given a list of parallel spike trains, estimate the cumulative probability\n of each entry in their intersection matrix (see: intersection_matrix())\nby a Monte Carlo approach using surrogate data.\nContrarily to the analytical version (see: probability_matrix_analytical())\nthe Monte Carlo one does not incorporate the assumptions of Poissonianity\nin the null hypothesis.\n\nThe method produces surrogate spike trains (using one of several methods\nat disposal, see below) and calculates their intersection matrix M.\nFor each entry (i, j), the intersection cdf P[i, j] is then given by:\n\n.. centered::  P[i, j] = #(spike_train_surrogates such that M[i, j] < I[i, j]) /\n                    #(spike_train_surrogates)\n\nIf P[i, j] is large (close to 1), I[i, j] is statistically significant:\nthe probability to observe an overlap equal to or larger then I[i, j]\nunder the null hypothesis is 1-P[i, j], very small.\n\nParameters\n----------\nsts : list of neo.SpikeTrains\n    list of spike trains for which to compute the probability matrix\nbinsize : quantities.Quantity\n    width of the time bins used to compute the probability matrix\ndt : quantities.Quantity\n    time span for which to consider the given SpikeTrains\nt_start_x, t_start_y : quantities.Quantity, optional\n    time start of the binning for the first and second axes of the\n    intersection matrix, respectively.\n    If None (default) the attribute t_start of the SpikeTrains is used\n    (if the same for all spike trains).\n    Default: None\nsurr_method : str, optional\n    the method to use to generate surrogate spike trains. Can be one of:\n\n        * 'dither_spike_train': see spike_train_surrogates.train_shifting() [dt needed]\n        * 'spike_dithering': see spike_train_surrogates.spike_dithering() [dt needed]\n        * 'spike_jittering': see spike_train_surrogates.spike_jittering() [dt needed]\n        * 'spike_time_rand': see spike_train_surrogates.spike_time_rand()\n        * 'isi_shuffling': see spike_train_surrogates.isi_shuffling()\n\n    Default: 'dither_spike_train'\nj : quantities.Quantity, optional\n    For methods shifting spike times randomly around their original time\n    (spike dithering, train shifting) or replacing them randomly within a\n    certain window (spike jittering), j represents the size of that\n    shift / window. For other methods, j is ignored.\n    Default: None\nn_surr : int, optional\n    number of spike_train_surrogates to generate for the bootstrap\n    procedure. Default: 100\n\nReturns\n-------\npmat : ndarray\n    the cumulative probability matrix. pmat[i, j] represents the\n    estimated probability of having an overlap between bins i and j\n    STRICTLY LOWER than the observed overlap, under the null hypothesis\n    of independence of the input spike trains.\n\nSee also\n--------\nprobability_matrix_analytical() for analytical derivation of the matrix"
BUILDSTDERR: The full traceback has been saved in /tmp/sphinx-err-dwf_62a9.log, if you want to report the issue to the developers.
BUILDSTDERR: Please also report this if it was a user error, so that a better error message can be provided next time.
BUILDSTDERR: A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
BUILDSTDERR: make: *** [Makefile:45: html] Error 2

**Comment by dizcza** [comment] 2019-06-18 07:53
Duplicate of https://github.com/NeuralEnsemble/elephant/issues/224.
Or rather vice versa.
It'll be fixed in https://github.com/NeuralEnsemble/elephant/pull/230.

**Closed** 2019-06-26 12:20 UTC
Labels: documentation, duplicate
